_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "../output/model_final.pth"
  MASK_ON: True
  RESNETS:
    NORM: "BN"
    DEPTH: 50
  FPN:
    NORM: "BN"
  PIXEL_MEAN: '[103.530, 116.280, 123.675]'
  PIXEL_STD: '[57.375, 57.120, 58.395]'
TEST:
  PRECISE_BN:
    ENABLED: True
